name: "build-test"
on: [push]

jobs:
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3 
    - name: Run Newman
      uses: anthonyvscode/newman-action@v1      
      id: run-api-tests
      with:
        apiKey: ${{ secrets.POSTMAN_API_KEY }}
        collection: ${{ secrets.POSTMAN_COLLECTION_ID }}
        environment: ${{ secrets.POSTMAN_ENVIRONMENT }}
        reporters: cli
    
    - name: Export Summary from Outputs
      run: echo ${{ steps.run-api-tests.outputs.summary_full }}
